CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE users(
	id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
	username VARCHAR (50) UNIQUE NOT NULL,
	email VARCHAR (355) UNIQUE NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);
